version: '3.7'

services:
  app:
    container_name: app12
    build:
      context: ./app
      dockerfile: Dockerfile
    image: homework12-app
    networks:
      - app-network

  nginx:
    container_name: nginx-proxy-12
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

